name: wisataanywhere
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  shimmer: ^3.0.0
  google_generative_ai: ^0.4.7
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  url_launcher: ^6.1.11
  permission_handler: ^11.3.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^19.2.1
  http: ^1.4.0
  liquid_pull_to_refresh: ^3.0.0
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/default_profile.png
flutter_icons:
  android: true
  ios: true
  image_path: assets/2.png